const translations = {
  ru: {
    title: "TransitFlow",
    banner_subtitle: "Логистика и цепи поставок",
    banner_title: "Самый безопасный поставщик логистики",
    banner_text: "Мы ведущий поставщик перевозок грузов с частичной загрузкой с мировой сетью, технологиями и сервисом для клиентов.",
    explore_more: "Подробнее",
    what_we_do: "Что мы делаем",
    service_title: "Безопасные и надежные грузоперевозки",
    sea_transport: "Морские транспортные услуги",
    sea_transport_text: "Мы организуем доставку вашего груза и остаемся конкурентными на рынке.",
    warehousing: "Складские услуги",
    warehousing_text: "У нас есть склады для распределения, хранения и управления заказами.",
    air_freight: "Авиагрузоперевозки",
    air_freight_text: "Мы сотрудничаем с авиалиниями и экспедиторами для авиадоставки по миру.",
    local_shipping: "Местные доставки",
    local_shipping_text: "Мы работаем с партнерами, чтобы обеспечить внутренние грузоперевозки.",
    why_us: "Почему мы",
    about_title: "Глобальные логистические решения",
    about_text_1: "Мы стремимся понять потребности клиентов, их цены и важные для них аспекты.",
    about_text_2: "Мы строим прочные отношения с клиентами, заботимся о них.",
    delivery_on_time: "Доставка вовремя",
    optimized_cost: "Оптимизированная цена",
    delivered_packages: "Доставленные посылки",
    satisfied_clients: "Довольные клиенты",
    work_title: "Перевозки по всему миру",
    liquid_transport: "Перевозка жидкостей",
    premium_tankers: "Премиум-цистерны",
    packaging_solutions: "Решения для упаковки",
    warehouse_management: "Управление складом",
    contract_logistics: "Контрактная логистика",
    road_transportation: "Автомобильные перевозки",
    warehouse_distribution: "Склад и распределение",
    large_warehouse: "Большой склад",
    specialized_transport: "Специализированные перевозки",
    ocean_transports: "Океанские перевозки",
    more_work: "Больше работ",
    customer_reviews: "Отзывы клиентов",
    what_customers_say: "Что говорят клиенты",
    comment_1: "«Склады TransitFlow эффективны и безопасны. Рекомендую!»",
    comment_2: "«TransitFlow улучшил нашу логистику! Отслеживание в реальном времени сократило расходы, а команда помогла с интеграцией.»",
    comment_3: "«TransitFlow быстро выполнил срочную доставку. Склады отличные, персонал всегда на связи!»",
    comment_4: "«С TransitFlow работаем год, их стабильность впечатляет. Управление запасами и доставки на высоте.»",
    comment_5: "«Логистика TransitFlow преобразила наш бизнес! Они справились с заказами в праздники, а отчеты улучшили нашу стратегию.»",
    why_choose: "Почему выбирают нас",
    features_title: "Раскрываем ваш бизнес-потенциал",
    features_text: "Мы ведущая фирма по логистике, предлагающая решения для складирования и транспортировки.",
    safe_package: "Безопасная упаковка",
    ship_everywhere: "Доставка повсюду",
    global_tracking: "Глобальное отслеживание",
    support_24_7: "Поддержка 24/7",
    in_time_delivery: "Своевременная доставка",
    transparent_pricing: "Прозрачное ценообразование",
    moving_products: "Перевозка товаров по миру",
    transporters: "Перевозчики",
    team_title: "Познакомьтесь с нашей командой",
    warehouse_head: "Руководитель склада",
    transport_manager: "Менеджер транспорта",
    cargo_head: "Руководитель грузов",
    contact: "Контакты",
    contact_title: "Свяжитесь с нами",
    contact_text: "Мы ценим ваш интерес! Заполните форму, и мы свяжемся для обсуждения ваших логистических нужд.",
    email: "Эл. почта",
    call_us: "Позвоните нам",
    mon_sat: "Пн-Сб 9:00-18:00, Вс выходной",
    submit_message: "Отправить сообщение",
    form_success: "Спасибо! Ваше сообщение получено!",
    form_error: "Ошибка при отправке формы!",
    our_blog: "Наш блог",
    blog_title: "Наши последние новости",
    read_more: "Читать дальше",
    blog_1_title: "Внутренние перевозки для бизнеса",
    blog_1_text: "Мы создаем ценность для клиентов с помощью современных технологий.",
    urgent_transport: "Срочные транспортные решения",
    sea_transport: "Морские транспортные услуги",
    reliable_staff: "Надежный и опытный персонал",
    local_shipping: "Местные доставки",
    blog_2_title: "Как технологии меняют цепи поставок",
    blog_2_text: "Качество наших услуг завоевало доверие многих клиентов.",
    quality_service: "Качественные услуги по разумной цене",
    blog_3_title: "Пять вещей для вашего брокера",
    blog_3_text_1: "Наш опыт в логистике и передовые технологии",
    blog_3_text_2: "Решения помогут разработать успешные стратегии цепей поставок.",
    home: "Главная",
    login: "Войти",
    cart: "Корзина",
    catalog: "Каталог",
    favorites: "Избранное",
    our_team: "Наша команда",
    pricing: "Цены",
    blog: "Блог",
    about_us: "О нас",
    error_subtitle: "Ошибка",
    error_title: "Страница не найдена",
    error_message: "Упс! Страница не найдена.",
    error_description: "Страница не существует. Попробуйте другую или вернитесь на главную.",
    about_us_banner_title: "О нашей логистике",
    company_overview_title: "Обзор нашей компании",
    company_overview_text: "Глобальный охват, знания отрасли и технологии позволяют решать задачи клиентов.",
    our_approach: "Наш подход",
    our_approach_text: "Мы создаем инновационные решения для оптимизации цепей поставок клиентов.",
    our_goal: "Наша цель",
    our_goal_text: "Мы поддерживаем клиентов на каждом этапе: от бронирования до управления складами.",
    our_mission: "Наша миссия",
    our_mission_text: "Передовое решение, объединяющее все услуги в одном портале для поддержки цепей поставок.",
    team_member_1_name: "Хелен Уилмор",
    team_member_2_name: "Энтони Уиллс",
    team_member_3_name: "Кейт Уинслот",
    commentator_1_name: "Лио Джессика",
    commentator_1_country: "Великобритания",
    commentator_2_name: "Майкл Чен",
    commentator_2_country: "Сингапур",
    commentator_3_name: "София Родригес",
    commentator_3_country: "Испания",
    commentator_4_name: "Ахмед Халид",
    commentator_4_country: "ОАЭ",
    commentator_5_name: "Эмили Джонсон",
    commentator_5_country: "США",
    pricing_title: "Наши лучшие цены",
    basic_plan: "Базовый",
    per_month: "/месяц",
    single_truck: "Один грузовик",
    full_insurance: "Полная страховка",
    distance_500km: "500 км",
    real_time_rate: "Тарифы в реальном времени",
    standard_plan: "Стандартный",
    double_truck: "Два грузовика",
    distance_1000km: "1000 км",
    premium_plan: "Премиум",
    unlimited_distance: "Безлимитный пробег",
    choose_plan: "Выбрать план",
    faq: "Часто задаваемые вопросы",
    faq_title: "Часто задаваемые вопросы",
    faq_question_1: "Какие гарантии для моих отправлений?",
    faq_answer_1: "Мы работаем по стандартам отрасли и предлагаем страховку по запросу.",
    faq_question_2: "Что такое коммуникационный сбор?",
    faq_answer_2: "Сбор включает записи в онлайн-каталоге и доступ к пресс-разделам.",
    faq_question_3: "Какие логистические планы доступны?",
    faq_answer_3: "Важно, чтобы ваш партнер понимал ваши бизнес-требования.",
    faq_question_4: "Могу ли я выбрать дату доставки?",
    faq_answer_4: "Поставщик должен соответствовать культуре вашей компании.",
    lets_talk: "Давай поговорим",
    faq_contact_title: "Нужна помощь? Бесплатная консультация",
    have_questions: "Есть вопросы",
    phone_number: "(00) 123 456 789",
    admin_title: "Админ TransitFlow",
    admin_panel: "Панель управления",
    admin_user: "Пользователь-админ",
    users_tab: "Пользователи",
    services_tab: "Услуги",
    manage_users: "Управление пользователями",
    search_users_placeholder: "Поиск пользователей...",
    sort_by_id: "Сортировать по ID",
    sort_by_email: "Сортировать по email",
    sort_by_first_name: "Сортировать по имени",
    users_list: "Список пользователей",
    table_id: "ID",
    table_email: "Email",
    table_first_name: "Имя",
    table_last_name: "Фамилия",
    table_middle_name: "Отчество",
    table_phone: "Телефон",
    table_birthdate: "Дата рождения",
    table_nickname: "Псевдоним",
    table_role: "Роль",
    table_actions: "Действия",
    add_user: "Добавить пользователя",
    manage_services: "Управление услугами",
    search_services_placeholder: "Поиск услуг...",
    sort_by_name: "Сортировать по названию",
    sort_by_price: "Сортировать по цене",
    services_list: "Список услуг",
    table_name: "Название",
    table_price: "Цена",
    table_description: "Описание",
    add_service: "Добавить услугу",
    close: "Закрыть",
    selected_services: "Выбранные услуги",
    total: "Итого",
    proceed_checkout: "Оплатить",
    empty_cart: "Корзина пуста",
    empty_cart_text: "Просмотрите услуги и добавьте товары.",
    explore_services: "Изучить услуги",
    order_summary: "Сводка заказа",
    subtotal: "Промежуточный итог",
    estimated_shipping: "Оценочная доставка",
    insurance: "Страховка",
    filters: "Фильтры",
    category: "Категория",
    category_all: "Все",
    category_transport: "Транспорт",
    category_logistics: "Логистика",
    category_equipment: "Оборудование",
    category_technology: "Технологии",
    category_safety: "Безопасность",
    category_specialized: "Специализированные",
    category_additional: "Дополнительные",
    price: "Цена",
    price_from_placeholder: "От",
    price_to_placeholder: "До",
    min_rating: "Минимальный рейтинг",
    rating_any: "Любой",
    rating_4: "4.0+",
    rating_4_5: "4.5+",
    reset_filters: "Сбросить фильтры",
    catalog_title: "Каталог услуг",
    sort_by: "Сортировать по:",
    sort_price_asc: "Цена: по возрастанию",
    sort_price_desc: "Цена: по убыванию",
    sort_rating_desc: "Рейтинг: по убыванию",
    sort_name_asc: "Название: А-Я",
    favorite_services: "Избранные услуги",
    secure_access: "Безопасный доступ",
    welcome_back: "С возвращением",
    enter_credentials: "Введите данные для входа в аккаунт",
    email_placeholder: "Адрес эл. почты*",
    password_placeholder: "Пароль*",
    sign_in: "Войти",
    no_account: "Нет аккаунта?",
    create_account: "Создать аккаунт",
    your_profile: "Ваш профиль",
    manage_account: "Управление аккаунтом",
    nickname: "Никнейм",
    nickname_placeholder: "Никнейм",
    save_changes: "Сохранить изменения",
    logout: "Выйти",
    changes_saved: "Изменения успешно сохранены!",
    fill_required_fields: "Заполните все обязательные поля",
    first_name: "Имя *",
    first_name_placeholder: "Имя *",
    last_name: "Фамилия *",
    last_name_placeholder: "Фамилия *",
    middle_name: "Отчество",
    middle_name_placeholder: "Отчество (необяз.)",
    phone_number_by: "Телефон (BY) *",
    phone_placeholder: "+375291234567",
    birthdate: "Дата рождения *",
    birthdate_placeholder: "Дата рождения *",
    password_selection_method: "Способ выбора пароля *",
    enter_manually: "Ввести вручную",
    generate_automatically: "Сгенерировать авто",
    confirm_password_placeholder: "Подтвердите пароль *",
    accept_terms: "Я принимаю условия",
    user_agreement: "Пользовательское соглашение",
    register: "Зарегистрироваться",
    back_to_catalog: "← Назад к каталогу",
    pages: "Страницы",
    settings: "Настройки",
    language: "Язык",
    theme: "Тема",
    footer_mission: "Быть лидером отрасли, предлагая эффективные и качественные решения.",
    utility: "Утилиты",
    subscribe: "Подписаться",
    send_now: "Отправить сейчас",
    style_guide: "Руководство по стилю",
    changelog: "Журнал изменений",
    licenses: "Лицензии",
    protected: "Защищено",
    not_found: "Не найдено",
    password: "Пароль",
    our_project: "Наш проект",
    more_blog: "Больше блогов",
    secure_payment: "Безопасный платеж",
    no_data: "Нет данных",
    edit: "Изменить",
    delete: "Удалить",
    save: "Сохранить",
    form_not_found: "Форма не найдена",
    correct_errors: "Исправьте ошибки в данных",
    user_not_found: "Пользователь не найден",
    invalid_password: "Неверный пароль",
    login_error: "Произошла ошибка входа",
    login_success: "Вход выполнен успешно!",
    please_login: "Пожалуйста, войдите в аккаунт",
    catalog_load_error: "Ошибка загрузки каталога. Попробуйте позже.",
    catalog_init_error: "Ошибка инициализации каталога",
    catalog_grid_missing: "Элемент catalog-grid не найден в DOM",
    element_missing: "Элемент не найден в DOM",
    pagination_elements_missing: "Элементы пагинации отсутствуют в DOM",
    login_form_missing: "Форма входа не найдена",
    user_role_undefined: "Роль пользователя не определена",
    required_elements_missing: "Необходимые элементы шапки не найдены",
    redirect_to_login: "Перенаправление на страницу входа",
    redirect_after_login: "Перенаправление после входа на страницу профиля",
    blocked_navigation: "Навигация заблокирована",
    invalid_url: "Недействительный URL",
    user_already_exists_email: "Пользователь с таким email уже существует",
    user_already_exists_phone: "Пользователь с таким номером телефона уже существует",
    user_creation_failed: "Не удалось создать пользователя",
    user_update_failed: "Не удалось обновить данные пользователя",
    user_deletion_failed: "Не удалось удалить пользователя",
    service_creation_failed: "Не удалось создать услугу",
    service_update_failed: "Не удалось обновить услугу",
    service_deletion_failed: "Не удалось удалить услугу",
    users_load_error: "Ошибка загрузки пользователей",
    services_load_error: "Ошибка загрузки услуг",
    user_data_load_error: "Ошибка загрузки данных пользователя",
    user_update_error: "Ошибка обновления профиля",
    user_not_authorized: "Пользователь не авторизован",
    add_to_cart_login_required: "Пожалуйста, войдите в аккаунт для добавления в корзину",
    add_to_favorites_login_required: "Пожалуйста, войдите в аккаунт для добавления в избранное",
    initialization_error: "Ошибка инициализации",
    empty_cart_message: "Ваша корзина пуста", // Для .empty-cart-message
    explore_services_button: "Изучить услуги", // Для кнопки в .empty-cart-message
    quantity: "Количество", // Для .cart-item-quantity span
    subtotal_label: "Промежуточный итог", // Для .cart-item-subtotal
    remove_button: "Удалить", // Для .remove-btn
    details_button: "Подробности", // Для .details-btn
    add_to_cart_button: "Добавить в корзину", // Для .add-to-cart-btn
    checkout_button: "Оформить заказ", // Для .checkout-btn
    order_summary_title: "Сводка заказа", // Для .cart-summary
    estimated_shipping_label: "Оценочная доставка", // Для .summary-row
    insurance_label: "Страховка", // Для .summary-row
    total_label: "Итого", // Для .summary-row.total
    payment_methods_label: "Способы оплаты", // Для .payment-methods p
    confirm_delete_user: "Вы уверены, что хотите удалить этого пользователя?", // Для confirm в delete-user
    confirm_delete_service: "Вы уверены, что хотите удалить эту услугу?", // Для confirm в delete-service
    user_deleted_success: "Пользователь успешно удален", // Для успешного удаления пользователя
    service_deleted_success: "Услуга успешно удалена", // Для успешного удаления услуги
    our_contacts: "Где нас найти",
    accessibility_settings: "Настройки для слабовидящих",
    small_font: "Маленький шрифт",
    medium_font: "Средний шрифт",
    large_font: "Большой шрифт", 
    white_black_scheme: "Белый фон, черный текст",
    dark_white_scheme: "Темный фон, белый текст",
    dark_green_scheme: "Темный фон, зеленый текст",
    beige_brown_scheme: "Бежевый фон, коричневый текст",
    blue_darkblue_scheme: "Синий фон, темно-синий текст",
    toggle_images: "Переключить изображения", 
    reset_settings: "Сбросить настройки",
    confirm_reset_settings: "Вы уверены, что хотите сбросить все настройки?",
    settings_reset_success: "Настройки успешно сброшены!",
    modal_success: "Успешно!",
    modal_error: "Ошибка!",
    modal_info: "Информация",
    modal_warning: "Предупреждение",
    modal_close: "Закрыть",
    modal_ok: "ОК",
    modal_cancel: "Отмена",
    modal_confirm: "Подтвердить",
    modal_yes: "Да",
    modal_no: "Нет",
    user_agreement_title: "Пользовательское соглашение",
    user_agreement_content: "<h4>1. Общие положения</h4><p>1.1. Использование сайта TransitFlow означает безоговорочное согласие Пользователя с настоящим Соглашением и указанными в нем условиями.</p><p>1.2. В случае несогласия с условиями Соглашения Пользователь должен прекратить использование сайта.</p><h4>2. Предмет соглашения</h4><p>2.1. Администрация предоставляет Пользователю услуги по использованию сайта TransitFlow на условиях, являющихся предметом настоящего Соглашения.</p><p>2.2. Сайт TransitFlow предоставляет информационные услуги в области логистики и грузоперевозок.</p><h4>3. Права и обязанности сторон</h4><p>3.1. Пользователь имеет право использовать функциональные возможности сайта в соответствии с его назначением.</p><p>3.2. Пользователь обязуется не нарушать права третьих лиц при использовании сайта.</p><p>3.3. Администрация обязуется обеспечивать работоспособность сайта в пределах разумного.</p><h4>4. Ответственность</h4><p>4.1. Администрация не несет ответственности за временные технические сбои и перерывы в работе сайта.</p><p>4.2. Пользователь несет полную ответственность за достоверность предоставляемой информации.</p><h4>5. Заключительные положения</h4><p>5.1. Администрация оставляет за собой право в одностороннем порядке изменять условия настоящего Соглашения.</p><p>5.2. Настоящее Соглашение регулируется и толкуется в соответствии с законодательством Республики Беларусь.</p>",
    copyright: "© 2024 TransitFlow. Все права защищены."
  },
  en: {
    title: "TransitFlow",
    banner_subtitle: "Logistics & Supply Chain Solutions",
    banner_title: "Safest Logistics Solutions Provider With Integrity",
    banner_text: "We're a leading provider of less-than-truckload freight transportation with the world-class network, technology and service our customers need at all the time.",
    explore_more: "Explore More",
    what_we_do: "What We Do",
    service_title: "Safe & Reliable Cargo Solutions",
    sea_transport: "Sea Transport Services",
    sea_transport_text: "Wherever your cargo is going, we can arrange the shipment for you and remain competitive with the business market.",
    warehousing: "Warehousing Services",
    warehousing_text: "We have buildings that can provide you with distribution, storage, inventory management, order fulfilment services.",
    air_freight: "Air Fright Services",
    air_freight_text: "We're partners with airlines and freight forwarders to offer seamless air freight solutions to the clients all over the world.",
    local_shipping: "Local Shipping Services",
    local_shipping_text: "We work close with strategic partners to ensure our domestic trucking offers clients everything they need in their place.",
    why_us: "Why Us",
    about_title: "We provide full range global logistics solution",
    about_text_1: "We strive to understand what they need, what their price points are, and what's important to them.",
    about_text_2: "We build meaningful relationships with our customers. We care.",
    delivery_on_time: "Delivery on Time",
    optimized_cost: "Optimized Travel Cost",
    delivered_packages: "Delivered Packages",
    satisfied_clients: "Satisfied Clients",
    work_title: "Transporting across the world",
    liquid_transport: "Liquid Transportation",
    premium_tankers: "Premium Tankers",
    packaging_solutions: "Packaging Solutions",
    warehouse_management: "Warehouse Management",
    contract_logistics: "Contract Logistics",
    road_transportation: "Road Transportation",
    warehouse_distribution: "Warehouse & Distribution",
    large_warehouse: "Large Warehouse",
    specialized_transport: "Specialized Transport",
    ocean_transports: "Ocean Transports",
    more_work: "More Work",
    customer_reviews: "Customer Reviews",
    what_customers_say: "What Our Customers Say",
    comment_1: "“The warehousing solutions provided by TransitFlow are efficient and secure. Highly recommend!”",
    comment_2: "“TransitFlow transformed our supply chain management! Their real-time tracking system allowed us to optimize delivery routes and reduce costs significantly.”",
    comment_3: "“I was impressed by how quickly TransitFlow handled our last-minute shipment needs. Their warehousing facilities are top-notch, and the staff is always ready to assist. They’ve become our go-to logistics partner!”",
    comment_4: "“We've been working with TransitFlow for over a year, and their consistency is unmatched. From inventory management to timely deliveries, they've helped us streamline our operations.”",
    comment_5: "“TransitFlow's logistics solutions have been a game-changer for our e-commerce business. Their ability to handle large volumes of orders during the holiday season was impressive. Highly recommend their services!”",
    why_choose: "Why Choose",
    features_title: "We create an opportunity to reach business potential",
    features_text: "Logistics is a distinguished supply chain management firm providing comprehensive solutions for warehousing and transportation.",
    safe_package: "Safe Package",
    ship_everywhere: "Ship Everywere",
    global_tracking: "Global Tracking",
    support_24_7: "24/7 Support",
    in_time_delivery: "In Time Delivery",
    transparent_pricing: "Transparent Pricing",
    moving_products: "Moving your products across world",
    transporters: "The Transporters",
    team_title: "Meet Expert Team",
    warehouse_head: "Warehouse Head",
    transport_manager: "Transport Manager",
    cargo_head: "Cargo head",
    contact: "Contact",
    contact_title: "Get in touch with us",
    contact_text: "We appreciate your interest. Please complete the form below and we will contact you to discuss your logistics needs.",
    email: "Email",
    call_us: "Call Us",
    mon_sat: "Mon - Sat 9.00 - 18.00 Sunday Closed",
    submit_message: "Submit Message",
    form_success: "Thank you! Your submission has been received!",
    form_error: "Oops! Something went wrong while submitting the form.",
    our_blog: "Our Blog",
    blog_title: "Our Latest News",
    read_more: "Read More",
    blog_1_title: "Inland freight a worthy solution for your business",
    blog_1_text: "We are dedicated in creating added value for our customers by implementing modern technology in our work.",
    urgent_transport: "Urgent transport solutions",
    sea_transport: "Sea Transport Services",
    reliable_staff: "Reliable & experienced staffs",
    local_shipping: "Local Shipping Services",
    blog_2_title: "How technology can help redraw the supply chain map",
    blog_2_text: "Following the quality of our service thus having gained trust of our many clients.",
    quality_service: "Top quality services with reasonable price",
    blog_3_title: "Five things you should have ready for your broker",
    blog_3_text_1: "Our global logistics expertise, advanced supply chain technology & customized",
    blog_3_text_2: "Logistics solutions will help you analyze, develop and implement successful supply chain management strategies.",
    home: "Home",
    login: "Log In",
    cart: "Cart",
    catalog: "Catalog",
    favorites: "Favorites",
    our_team: "Our Team",
    pricing: "Pricing",
    blog: "Blog",
    about_us: "About Us",
    error_subtitle: "Error",
    error_title: "Page Not Found",
    error_message: "Oops! Page not found.",
    error_description: "The page you are looking for doesn't exist. Please try searching for some other page or return to the homepage.",
    about_us_banner_title: "About Our Logistics",
    company_overview_title: "Our Company Overview",
    company_overview_text: "Our global reach, deep industry knowledge, and innovative technology help us address our customers' unique challenges.",
    our_approach: "Our Approach",
    our_approach_text: "We leverage our scale to create innovative solutions that help our customers optimize their supply chains.",
    our_goal: "Our Goal",
    our_goal_text: "Whether you've been shipping for years or this is your first time, we're with you every step of the way.",
    our_mission: "Our Mission",
    our_mission_text: "Our most advanced logistic solution yet. It incorporates all eServices into one portal, giving you maximum support at every stage of your supply chain.",
    team_member_1_name: "Helen Wilmore",
    team_member_2_name: "Anthony Wills",
    team_member_3_name: "Kate Winslot",
    commentator_1_name: "Lio Jessica",
    commentator_1_country: "United Kingdom",
    commentator_2_name: "Michael Chen",
    commentator_2_country: "Singapore",
    commentator_3_name: "Sofia Rodriguez",
    commentator_3_country: "Spain",
    commentator_4_name: "Ahmed Khalid",
    commentator_4_country: "UAE",
    commentator_5_name: "Emily Johnson",
    commentator_5_country: "USA",
    pricing_title: "Our Best Pricing",
    basic_plan: "Basic",
    per_month: "/month",
    single_truck: "Single Truck",
    full_insurance: "Full Insurance",
    distance_500km: "500 Km",
    real_time_rate: "Real-time rate shopping",
    standard_plan: "Standard",
    double_truck: "Double Truck",
    distance_1000km: "1000 Km",
    premium_plan: "Premium",
    unlimited_distance: "Unlimited",
    choose_plan: "Choose Plan",
    faq: "FAQ",
    faq_title: "Frequently Asked Questions",
    faq_question_1: "What warranties do I have for my shipments?",
    faq_answer_1: "Logistics operates under country-specific freight forward industry terms. We are members of Logistics and Freight Association.",
    faq_question_2: "What is mandatory communication fee?",
    faq_answer_2: "The obligatory communication fee includes the basic entries in the online exhibitor directory and in the visit planner.",
    faq_question_3: "What options for logistics plans are available?",
    faq_answer_3: "The most important part of your logistics partnership is having confidence that your provider understands your business requirements.",
    faq_question_4: "Can I specify a delivery date when ordering?",
    faq_answer_4: "You want a supplier who does business in a way that aligns with your company's culture.",
    lets_talk: "Let's Talk",
    faq_contact_title: "You Need Any Help? Get Free Consultation",
    have_questions: "Have Any Questions",
    phone_number: "(00) 123 456 789",
    admin_title: "TransitFlow Admin",
    admin_panel: "Admin Panel",
    admin_user: "Admin User",
    users_tab: "Users",
    services_tab: "Services",
    manage_users: "Manage Users",
    search_users_placeholder: "Search users...",
    sort_by_id: "Sort by ID",
    sort_by_email: "Sort by Email",
    sort_by_first_name: "Sort by First Name",
    users_list: "Users List",
    table_id: "ID",
    table_email: "Email",
    table_first_name: "First Name",
    table_last_name: "Last Name",
    table_middle_name: "Middle Name",
    table_phone: "Phone",
    table_birthdate: "Birthdate",
    table_nickname: "Nickname",
    table_role: "Role",
    table_actions: "Actions",
    add_user: "Add User",
    manage_services: "Manage Services",
    search_services_placeholder: "Search services...",
    sort_by_name: "Sort by Name",
    sort_by_price: "Sort by Price",
    services_list: "Services List",
    table_name: "Name",
    table_price: "Price",
    table_description: "Description",
    add_service: "Add Service",
    close: "Close",
    selected_services: "Selected Services",
    total: "Total",
    proceed_checkout: "Pay",
    empty_cart: "Your cart is empty",
    empty_cart_text: "Browse our services and add items to get started",
    explore_services: "Explore Services",
    order_summary: "Order Summary",
    subtotal: "Subtotal",
    estimated_shipping: "Estimated Shipping",
    insurance: "Insurance",
    filters: "Filters",
    category: "Category",
    category_all: "All",
    category_transport: "Transport",
    category_logistics: "Logistics",
    category_equipment: "Equipment",
    category_technology: "Technology",
    category_safety: "Safety",
    category_specialized: "Specialized",
    category_additional: "Additional",
    price: "Price",
    price_from_placeholder: "From",
    price_to_placeholder: "To",
    min_rating: "Minimum Rating",
    rating_any: "Any",
    rating_4: "4.0+",
    rating_4_5: "4.5+",
    reset_filters: "Reset Filters",
    catalog_title: "Services Catalog",
    sort_by: "Sort by:",
    sort_price_asc: "Price: Low to High",
    sort_price_desc: "Price: High to Low",
    sort_rating_desc: "Rating: High to Low",
    sort_name_asc: "Name: A-Z",
    favorite_services: "Favorite Services",
    secure_access: "Secure Access",
    welcome_back: "Welcome Back",
    enter_credentials: "Please enter your credentials to access your account",
    email_placeholder: "Email Address*",
    password_placeholder: "Password*",
    sign_in: "Sign In",
    no_account: "Don’t have an account?",
    create_account: "Create Account",
    your_profile: "Your Profile",
    manage_account: "Manage Account",
    email: "Email",
    nickname: "Nickname",
    nickname_placeholder: "Nickname",
    save_changes: "Save Changes",
    logout: "Log Out",
    changes_saved: "Changes Saved Successfully!",
    fill_required_fields: "Please fill in all required fields",
    first_name: "First Name *",
    first_name_placeholder: "First Name *",
    last_name: "Last Name *",
    last_name_placeholder: "Last Name *",
    middle_name: "Middle Name",
    middle_name_placeholder: "Middle Name (optional)",
    phone_number_by: "Phone Number (BY) *",
    phone_placeholder: "+375291234567",
    birthdate: "Date of Birth *",
    birthdate_placeholder: "Date of Birth *",
    password_selection_method: "Password Selection Method *",
    enter_manually: "Enter Manually",
    generate_automatically: "Generate Automatically",
    confirm_password_placeholder: "Confirm Password *",
    accept_terms: "I accept the terms of the",
    user_agreement: "User Agreement",
    register: "Register",
    back_to_catalog: "← Back to Catalog",
    pages: "Pages",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    footer_mission: "To be the industry leader, globally recognized for effective & efficient solutions. To provide innovative solutions delivering quality, excellence and speed.",
    utility: "Utility",
    subscribe: "Subscribe",
    send_now: "Send Now",
    style_guide: "Style Guide",
    changelog: "Changelog",
    licenses: "Licenses",
    protected: "Protected",
    not_found: "Not Found",
    password: "Password",
    our_project: "Our Project",
    more_blog: "More Blog",
    secure_payment: "Secure Payment",
    no_data: "No data",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    form_not_found: "Form not found",
    correct_errors: "Please correct the errors in the form",
    user_not_found: "User not found",
    invalid_password: "Invalid password",
    login_error: "An error occurred during login",
    login_success: "Login successful!",
    please_login: "Please log in to your account",
    catalog_load_error: "Error loading catalog. Please try again later.",
    catalog_init_error: "Catalog initialization error",
    catalog_grid_missing: "Element catalog-grid not found in DOM",
    element_missing: "Element not found in DOM",
    pagination_elements_missing: "Pagination elements are missing in the DOM",
    login_form_missing: "Login form not found",
    user_role_undefined: "User role is undefined",
    required_elements_missing: "Required header elements not found",
    redirect_to_login: "Redirecting to login page",
    redirect_after_login: "Redirecting to profile page after login",
    blocked_navigation: "Navigation blocked",
    invalid_url: "Invalid URL",
    user_already_exists_email: "User with this email already exists",
    user_already_exists_phone: "User with this phone number already exists",
    user_creation_failed: "Failed to create user",
    user_update_failed: "Failed to update user data",
    user_deletion_failed: "Failed to delete user",
    service_creation_failed: "Failed to create service",
    service_update_failed: "Failed to update service",
    service_deletion_failed: "Failed to delete service",
    users_load_error: "Error loading users",
    services_load_error: "Error loading services",
    user_data_load_error: "Error loading user data",
    user_update_error: "Error updating profile",
    user_not_authorized: "User not authorized",
    add_to_cart_login_required: "Please log in to add to cart",
    add_to_favorites_login_required: "Please log in to add to favorites",
    initialization_error: "Initialization error",
    empty_cart_message: "Your cart is empty", // Для .empty-cart-message
    explore_services_button: "Explore Services", // Для кнопки в .empty-cart-message
    quantity: "Quantity", // Для .cart-item-quantity span
    subtotal_label: "Subtotal", // Для .cart-item-subtotal
    remove_button: "Remove", // Для .remove-btn
    details_button: "Details", // Для .details-btn
    add_to_cart_button: "Add to Cart", // Для .add-to-cart-btn
    checkout_button: "Checkout", // Для .checkout-btn
    order_summary_title: "Order Summary", // Для .cart-summary
    estimated_shipping_label: "Estimated Shipping", // Для .summary-row
    insurance_label: "Insurance", // Для .summary-row
    total_label: "Total", // Для .summary-row.total
    payment_methods_label: "Payment Methods", // Для .payment-methods p
    confirm_delete_user: "Are you sure you want to delete this user?", // Для confirm в delete-user
    confirm_delete_service: "Are you sure you want to delete this service?", // Для confirm в delete-service
    user_deleted_success: "User successfully deleted", // Для успешного удаления пользователя
    service_deleted_success: "Service successfully deleted",
    our_contacts: "Find Us",
    accessibility_settings: "Accessibility Settings",
    small_font: "Small Font",
    medium_font: "Medium Font", 
    large_font: "Large Font",
    white_black_scheme: "White background, black text",
    dark_white_scheme: "Dark background, white text",
    dark_green_scheme: "Dark background, green text",
    beige_brown_scheme: "Beige background, brown text", 
    blue_darkblue_scheme: "Blue background, dark blue text",
    toggle_images: "Toggle Images",
    reset_settings: "Reset Settings",
    confirm_reset_settings: "Are you sure you want to reset all settings?",
    settings_reset_success: "Settings successfully reset!",
    modal_success: "Success!",
    modal_error: "Error!",
    modal_info: "Information",
    modal_warning: "Warning",
    modal_close: "Close",
    modal_ok: "OK",
    modal_cancel: "Cancel",
    modal_confirm: "Confirm",
    modal_yes: "Yes",
    modal_no: "No",
    user_agreement_title: "User Agreement",
    user_agreement_content: "<h4>1. General Provisions</h4><p>1.1. Use of the TransitFlow website implies unconditional consent of the User to this Agreement and the conditions specified therein.</p><p>1.2. In case of disagreement with the terms of the Agreement, the User must stop using the website.</p><h4>2. Subject of the Agreement</h4><p>2.1. The Administration provides the User with services for using the TransitFlow website on the terms that are the subject of this Agreement.</p><p>2.2. The TransitFlow website provides information services in the field of logistics and freight transportation.</p><h4>3. Rights and Obligations of the Parties</h4><p>3.1. The User has the right to use the functional capabilities of the website in accordance with its purpose.</p><p>3.2. The User undertakes not to violate the rights of third parties when using the website.</p><p>3.3. The Administration undertakes to ensure the operability of the website within reasonable limits.</p><h4>4. Liability</h4><p>4.1. The Administration is not responsible for temporary technical failures and interruptions in the website operation.</p><p>4.2. The User bears full responsibility for the accuracy of the information provided.</p><h4>5. Final Provisions</h4><p>5.1. The Administration reserves the right to unilaterally change the terms of this Agreement.</p><p>5.2. This Agreement is governed by and construed in accordance with the laws of the Republic of Belarus.</p>",
    copyright: "© 2024 TransitFlow. All rights reserved."
  }
};

let currentLanguage = localStorage.getItem("language") || "ru";

function setLanguage(lang) {
    currentLanguage = lang;
    localStorage.setItem("language", lang);
    applyTranslations(lang);
    window.dispatchEvent(new Event('languageChanged'));
}

function applyTranslations(lang) {
    const elements = document.querySelectorAll("[data-translate-key]");

    elements.forEach(el => {
        if (el.tagName.toLowerCase() === 'html') {
            console.warn(`Skipping translation for <html> element with key: ${el.getAttribute("data-translate-key")}`);
            return;
        }

        const key = el.getAttribute("data-translate-key");
        if (translations[lang] && translations[lang][key]) {
            if (el.tagName === "INPUT" && el.type === "submit") {
                el.value = translations[lang][key];
            } else if (el.tagName === "INPUT" && el.hasAttribute('placeholder')) {
                el.placeholder = translations[lang][key];
            } else {
                el.textContent = translations[lang][key];
            }
        } else {
            console.warn(`Translation missing for key: ${key} in language: ${lang}`);
        }
    });

    const radios = document.querySelectorAll("input[name='language']");
    radios.forEach(radio => {
        radio.checked = (radio.value === lang);
    });
}

function setupLanguageToggle() {
    const initRadios = (attempt = 1, maxAttempts = 5) => {
        const radios = document.querySelectorAll("input[name='language']");
        if (radios.length === 0) {
            if (attempt >= maxAttempts) {
                console.error('Language radio buttons not found');
                return;
            }
            console.warn('Language radio buttons not found, retrying...');
            setTimeout(() => initRadios(attempt + 1, maxAttempts), 100);
            return;
        }

        radios.forEach(radio => {
            radio.addEventListener("change", () => {
                setLanguage(radio.value);
            });
        });

        applyTranslations(currentLanguage);
    };

    if (document.getElementById('header-content')?.innerHTML.trim()) {
        initRadios();
    } else {
        document.addEventListener('headerLoaded', () => {
            initRadios();
        }, { once: true });
    }

    let isTranslating = false;
    const observer = new MutationObserver((mutations) => {
        if (isTranslating) return;
        isTranslating = true;
        mutations.forEach(mutation => {
            if (mutation.addedNodes.length) {
                mutation.addedNodes.forEach(node => {
                    if (node.nodeType === Node.ELEMENT_NODE && node.querySelector('[data-translate-key]')) {
                        applyTranslations(currentLanguage);
                    }
                });
            }
        });
        isTranslating = false;
    });
    observer.observe(document.body, { childList: true, subtree: true });
}

window.translatePage = () => {
    applyTranslations(currentLanguage);
};

window.translations = translations;

document.addEventListener('headerLoaded', setupLanguageToggle, { once: true });